/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GreeterInterface extends Interface {
  getFunction(
    nameOrSignature: "certification" | "getCertification" | "setCertification"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "certification",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCertification",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCertification",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "certification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCertification",
    data: BytesLike
  ): Result;
}

export interface Greeter extends BaseContract {
  connect(runner?: ContractRunner | null): Greeter;
  waitForDeployment(): Promise<this>;

  interface: GreeterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  certification: TypedContractMethod<[], [string], "view">;

  getCertification: TypedContractMethod<[], [string], "view">;

  setCertification: TypedContractMethod<
    [_certification: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "certification"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCertification"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setCertification"
  ): TypedContractMethod<[_certification: string], [void], "nonpayable">;

  filters: {};
}
